"""Write the input system out as a STANDALONE folder.

    .venv/Scripts/python.exe handinput/export_package.py <target-dir>

⭐ THIS IS THE ANSWER TO "can I copy-paste it into another app". The estimator
modules stay where they are in this repo (see `manifest.py` for why), so the
export is what turns the manifest into a folder you can drop into another Python
project -- or read alongside while transliterating to TypeScript, C# or Swift.

Layout produced:

    <target>/handinput/…            this package, verbatim
    <target>/handinput/core/…       the manifest's estimator modules
    <target>/handinput/conformance/ vectors + traces, so the copy is TESTABLE

⚠ THE COPY IS NOT A FORK. It is generated, and re-generating overwrites it. Edit
the originals; never the export. An export that has been edited is a second
implementation with no harness pointed at it -- the exact failure mode this
project keeps paying for.

⚠ `core/` gets a tiny `__init__.py` and NOTHING ELSE is rewritten: every module
in the manifest already carries the `try: from . import x / except ImportError:
import x` idiom, so the same file works as a package member and as a flat module
on `sys.path`. That idiom is why this export is a copy rather than a port.
"""
import os
import shutil
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(_HERE))

from handinput import manifest, __version__      # noqa: E402

_CORE_INIT = '''"""The portable estimator core -- GENERATED by handinput/export_package.py.

⛔ DO NOT EDIT. Edit the originals in the vision pipeline repo and re-export.
Source of each file and the reason this list is what it is: `handinput/manifest.py`.
"""
'''

_SKIP_DIRS = {"__pycache__"}


def _copy_package(target):
    dst = os.path.join(target, "handinput")
    for root, dirs, files in os.walk(_HERE):
        dirs[:] = [d for d in dirs if d not in _SKIP_DIRS]
        rel = os.path.relpath(root, _HERE)
        out = dst if rel == "." else os.path.join(dst, rel)
        os.makedirs(out, exist_ok=True)
        for f in files:
            if f.endswith(".pyc"):
                continue
            shutil.copy2(os.path.join(root, f), os.path.join(out, f))
    return dst


def main(argv):
    if len(argv) != 2:
        print(__doc__)
        return 2
    target = os.path.abspath(argv[1])

    gone = manifest.missing()
    if gone:
        print("REFUSING TO EXPORT -- manifest entries not on disk:")
        for p in gone:
            print("   ", p)
        return 1

    os.makedirs(target, exist_ok=True)
    dst = _copy_package(target)

    core = os.path.join(dst, "core")
    os.makedirs(core, exist_ok=True)
    with open(os.path.join(core, "__init__.py"), "w", encoding="utf-8") as fh:
        fh.write(_CORE_INIT)
    for name, path in manifest.MODULES:
        shutil.copy2(path, os.path.join(core, name + ".py"))

    n_core = len(manifest.MODULES)
    lines = sum(sum(1 for _ in open(p, encoding="utf-8")) for p in manifest.module_paths())
    print("handinput %s exported to %s" % (__version__, dst))
    print("  package  : contract, actions, config, sources, conformance")
    print("  core     : %d modules, %d lines (stdlib-only, numpy-free)" % (n_core, lines))
    print()
    print("  To use it, put core/ on the path (or import handinput.core.* ) and:")
    print("      from handinput import HandInput")
    print("  To prove the copy is faithful, run its conformance data against it.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
